### PR TITLE
add ATS-0.2.7 version

### PR DESCRIPTION
**Pull request by steinwaywhw**
Hi, I rebuilt the latest version to sync with upstream ATS language. And retain the old one in a separate 0.2.7 version for compatibility. I didn't test this, but it seems ok. I hope it will cause no problem. 

Thank you.

### CODE REVIEW

**Comment by prasmussen** [comment]
As a general rule I only want to keep older major versions of a language and only if it's not backwards compatible with the latest versions.

**Comment by prasmussen** [comment]
By the way, the ATS image is pretty large in filesize. I see that a lot of other languages are installed in the same image, i.e. nodejs, clojure and erlang – is there a reason for this? I would prefer that only needed packages are installed in the images.

**Comment by steinwaywhw** [comment]
ATS is more of a language front-end. It can be co-programmed and compiled into a target language, and run by the target language. Currently it supports erlang/elixir, python, closure, scheme, php, javascript, C (primary). That is way it need to install those as well. 

I can consider separating them into different versions for user to select from. Say "ats-erlang" version can run erlang, "ats-javascript" version can run javascript, etc. If this is what you prefer, I will go ahead and create those images for you. 

ATS is mostly backwards compatible. I can delete the old version. The only reason I keep that is I have some public code hosted on glot.io that uses an old version of an ATS tool. The tool is not backwards compatible. But I can migrate my own code though.

**Comment by prasmussen** [comment]
Ah, I see. That's fine then, no need to create separate images :)

I don't want to manage several 0.\* images of a image though, so I will close this PR.

**Comment by steinwaywhw** [comment]
Sure, thank you!

**Pull request closed without merging**
